
# config/thresholds.yaml
# يحدد العتبات اللازمة لتفعيل "صوت" كل شبكة أخلاقية في محرك الاستدلال.

# عتبات التفعيل الأساسية (Activation Thresholds)
# إذا كانت درجة الثقة في تحليل الشبكة أعلى من هذا الرقم، يتم أخذها بعين الاعتبار.
base_thresholds:
  UtiliNet: 0.75  # شبكة المنفعة
  DeontoNet: 0.80 # شبكة الواجب
  VirtuNet: 0.70  # شبكة الفضيلة

# عتبة التحذير (Warning Threshold)
# إذا كانت درجة الثقة أقل من هذا الرقم، يشير محرك الاستدلال إلى عدم اليقين.
warning_threshold: 0.50

# عتبة التعارض الحاد (Severe Conflict Threshold)
# إذا اختلفت النتائج بدرجة أعلى من هذا، يتم تفعيل قواعد التعارض.
conflict_difference_threshold: 0.35
